### ISSUE TITLE
RedisCluster not supported for Redis version >= 7

### ISSUE THREAD

**Issue by adarshaj** [rediscala/rediscala#155]
The initialization of cluster nodes fails when there are slave nodes. The reason seems to be introduction of new field in redis reply to "CLUSTER SLOTS" command. Earlier there used to be 3 fields in output, now there are 4 fields (4th field being Networking Metadata Field). Also, redis protocol documentation recommends to use "CLUSTER SHARDS" going forward to find the shard configuration.

Actual exception thrown with relevant stacktrace is as follows:
```
[ERROR] [01/15/2024 15:14:18.973] [redis-rediscala.rediscala-client-worker-dispatcher-6] [akka://redis/user/RedisClientPool-$b/$a] null
java.util.NoSuchElementException                                                                                                                                                                 at redis.protocol.MultiBulk.toByteString(RedisProtocolReply.scala:67)
        at redis.api.clusters.ClusterSlots.buildClusterNode(Clusters.scala:23)                                                                                                                   at redis.api.clusters.ClusterSlots$$anonfun$$nestedInanonfun$decodeReply$1$1.$anonfun$applyOrElse$2(Clusters.scala:50)
        at scala.collection.Iterator$$anon$9.next(Iterator.scala:584)
        at scala.collection.immutable.List.prependedAll(List.scala:156)
        at scala.collection.immutable.List$.from(List.scala:684)
```

Ref:  https://redis.io/commands/cluster-slots/#:~:text=Starting%20with%20Redis%20version%207.0.0%3A%20Added%20additional%20networking%20metadata%20field.

For reference:
Redis < 7 outputs following:
```
cluster:6379> cluster slots
1) 1) (integer) 0
   2) (integer) 5460
   3) 1) "10.0.0.1"
      2) (integer) 6379
      3) "c795778ad79b31c33dc72f0e31a7e1816bfd91ef"
   4) 1) "10.0.0.2"
      2) (integer) 6379
      3) "e0a89498ea130f3851522ecc0b863466aab1175a"
2) 1) (integer) 5461
   2) (integer) 10922
   3) 1) "10.0.0.3"
      2) (integer) 6379
      3) "cbaa0c425218d8dcc4f750820347cd174a06c3ca"
   4) 1) "10.0.0.4"
      2) (integer) 6379
      3) "7ecf95c2f897c1b3bfdee901044068875b5b9949"
3) 1) (integer) 10923
   2) (integer) 16383
   3) 1) "10.0.0.5"
      2) (integer) 6379
      3) "b6d2dadd8b9c568e598838f3870b15ab98c0032e"
   4) 1) "10.0.0.6"
      2) (integer) 6379
      3) "12405ea32d0ee9a46670dce80707b9972bb4cd0e"
```

Redis >= 7 outputs following:
```
cluster:6379> cluster slots
1) 1) (integer) 0
   2) (integer) 5460
   3) 1) "10.0.0.1"
      2) (integer) 6379
      3) "56875bbb3ea5ca64d93a4774542e68ba01bb70c0"
      4) (empty array)
   4) 1) "10.0.0.2"
      2) (integer) 6379
      3) "f68b4cc8b4e671def98474eb499e37b556e5ed48"
      4) (empty array)
2) 1) (integer) 5461
   2) (integer) 10922
   3) 1) "10.0.0.3"
      2) (integer) 6379
      3) "311624d80544a18a783f95018a04d648940153b1"
      4) (empty array)
   4) 1) "10.0.0.4"
      2) (integer) 6379
      3) "4ca8aa0bd45eb1249541e32a7c0854fab2ee2637"
      4) (empty array)
3) 1) (integer) 10923
   2) (integer) 16383
   3) 1) "10.0.0.5"
      2) (integer) 6379
      3) "dbc3d4194b3e5e86af53b8c06594397957453436"
      4) (empty array)
   4) 1) "10.0.0.6"
      2) (integer) 6379
      3) "24950b95830bdc005191265e599e4716587aa06a"
      4) (empty array)
```

**Comment by zhaodaye2022** [comment]
一样的问题
